/**
 * All repos on your GitHub account (public + private + collaborator access).
 * updatedAt = last push activity on that repo.
 */
const CONTRIBUTION_ROLE =
  "Full-stack developer on the Inspire Wallet ecosystem — building wallet apps, admin dashboards, backend APIs, and payment gateway integrations across multiple teams.";

const FEATURED_PROJECTS = [
  {
    name: "IAM Inspire Wallet",
    githubRepo: "iamIwallet",
    owner: "EngrBrianDev",
    updatedAt: "2026-06-16T10:55:20Z",
    tag: "WALLET APP",
    description: "TypeScript wallet application — core Inspire Wallet client build under active development.",
    language: "TypeScript",
    tags: ["#TypeScript", "#InspireWallet", "#FinTech"],
    github: "https://github.com/EngrBrianDev/iamIwallet",
    private: true,
    horsepower: 880,
  },
  {
    name: "IM Wallet Admin",
    githubRepo: "imwalletadmin",
    owner: "EngrBrianDev",
    updatedAt: "2026-06-16T10:44:31Z",
    tag: "ADMIN PANEL",
    description: "Admin dashboard for IM Wallet — manage users, operations, and business configuration.",
    language: "TypeScript",
    tags: ["#TypeScript", "#Admin", "#Dashboard"],
    github: "https://github.com/EngrBrianDev/imwalletadmin",
    private: true,
    horsepower: 860,
  },
  {
    name: "IM Wallet Backend",
    githubRepo: "imwallet-backend",
    owner: "EngrBrianDev",
    updatedAt: "2026-06-16T10:41:58Z",
    tag: "BACKEND API",
    description: "Backend services for IM Wallet — handles business logic and operations across the platform.",
    language: "TypeScript",
    tags: ["#TypeScript", "#Node", "#Backend"],
    github: "https://github.com/EngrBrianDev/imwallet-backend",
    private: true,
    horsepower: 920,
  },
  {
    name: "Brighter Dental Clinic",
    githubRepo: "brighter-dental-clinic",
    owner: "Xicc29",
    updatedAt: "2026-07-23T00:00:00Z",
    tag: "FULL STACK",
    description: "Full-stack dental clinic web application — patient management, appointment booking, and clinic operations built end-to-end.",
    language: "TypeScript",
    tags: ["#TypeScript", "#FullStack", "#Healthcare", "#WebApp"],
    github: "https://github.com/Xicc29/brighter-dental-clinic",
    private: true,
    horsepower: 860,
  },
  {
    name: "Retro Garage Portfolio",
    githubRepo: "portfolio",
    owner: "Xicc29",
    updatedAt: "2026-07-23T14:47:45Z",
    tag: "SHOWROOM BUILD",
    description: "Interactive developer portfolio with retro cartoon racing garage theme, arcade games, and live GitHub sync.",
    language: "JavaScript",
    tags: ["#HTML", "#CSS", "#Tailwind", "#Canvas"],
    github: "https://github.com/Xicc29/portfolio",
    private: false,
    horsepower: 720,
  },
  {
    name: "Inspire Wallet V3",
    githubRepo: "InspirewalletV3",
    owner: "EngrBrianDev",
    updatedAt: "2026-06-13T02:26:08Z",
    tag: "WALLET APP",
    description: "Latest generation Inspire Wallet frontend — next-version client experience and feature set.",
    language: "TypeScript",
    tags: ["#TypeScript", "#InspireWallet", "#V3"],
    github: "https://github.com/EngrBrianDev/InspirewalletV3",
    private: true,
    horsepower: 900,
  },
  {
    name: "Inspire Admin V2",
    githubRepo: "inspireadmin2",
    owner: "EngrBrianDev",
    updatedAt: "2026-06-13T02:12:24Z",
    tag: "ADMIN PANEL",
    description: "Second-generation Inspire Wallet admin interface for internal team and operations management.",
    language: "TypeScript",
    tags: ["#TypeScript", "#Admin", "#InspireWallet"],
    github: "https://github.com/EngrBrianDev/inspireadmin2",
    private: true,
    horsepower: 850,
  },
  {
    name: "Seven I Wallet Backend",
    githubRepo: "SevenIWalletBackend",
    owner: "EngrBrianDev",
    updatedAt: "2026-06-13T02:08:18Z",
    tag: "BACKEND API",
    description: "Backend API layer for the Seven I Wallet product — server-side logic and data services.",
    language: "TypeScript",
    tags: ["#TypeScript", "#Backend", "#API"],
    github: "https://github.com/EngrBrianDev/SevenIWalletBackend",
    private: true,
    horsepower: 870,
  },
  {
    name: "Inspire Growth",
    githubRepo: "inspireGrowth",
    owner: "Rossyyyyyy",
    updatedAt: "2026-06-02T04:39:46Z",
    tag: "ANALYTICS",
    description: "Growth and analytics tooling for the Inspire Wallet ecosystem — tracking and expansion features.",
    language: "TypeScript",
    tags: ["#TypeScript", "#Analytics", "#Growth"],
    github: "https://github.com/Rossyyyyyy/inspireGrowth",
    private: true,
    horsepower: 780,
  },
  {
    name: "Inspire Wallet Web",
    githubRepo: "inspirewalletweb",
    owner: "EngrBrianDev",
    updatedAt: "2026-05-30T12:00:36Z",
    tag: "WALLET APP",
    description: "Web client for Inspire Wallet — browser-based wallet experience for end users.",
    language: "TypeScript",
    tags: ["#TypeScript", "#Web", "#InspireWallet"],
    github: "https://github.com/EngrBrianDev/inspirewalletweb",
    private: true,
    horsepower: 840,
  },
  {
    name: "IAM Inspire Wallet Admin",
    githubRepo: "iamIwalletAdmin",
    owner: "EngrBrianDev",
    updatedAt: "2026-05-04T11:27:18Z",
    tag: "ADMIN PANEL",
    description: "Administrative panel for the IAM Inspire Wallet platform — ops, config, and user management.",
    language: "TypeScript",
    tags: ["#TypeScript", "#Admin", "#InspireWallet"],
    github: "https://github.com/EngrBrianDev/iamIwalletAdmin",
    private: true,
    horsepower: 830,
  },
  {
    name: "Inspire Wallet Gateway (UPay)",
    githubRepo: "inspirewallet_gateway_upay_alpha",
    owner: "ultraelectronica",
    updatedAt: "2026-03-23T06:56:06Z",
    tag: "PAYMENT GATEWAY",
    description: "Payment gateway integration for Inspire Wallet using UPay — alpha-stage transaction processing.",
    language: "TypeScript",
    tags: ["#TypeScript", "#Payments", "#UPay"],
    github: "https://github.com/ultraelectronica/inspirewallet_gateway_upay_alpha",
    private: true,
    horsepower: 910,
  },
  {
    name: "Inspire Wallet Admin Backend",
    githubRepo: "inspirewalletadmin_backend",
    owner: "benedickcervantes",
    updatedAt: "2026-02-19T09:32:36Z",
    tag: "BACKEND API",
    description: "Server-side admin backend for Inspire Wallet — APIs powering the admin dashboard.",
    language: "JavaScript",
    tags: ["#JavaScript", "#Backend", "#Admin"],
    github: "https://github.com/benedickcervantes/inspirewalletadmin_backend",
    private: false,
    horsepower: 800,
  },
  {
    name: "Inspire Wallet V2",
    githubRepo: "inspirewalletv2",
    owner: "benedickcervantes",
    updatedAt: "2026-02-14T07:12:01Z",
    tag: "WALLET APP",
    description: "Version 2 Inspire Wallet application — core wallet features and user-facing flows.",
    language: "JavaScript",
    tags: ["#JavaScript", "#InspireWallet", "#V2"],
    github: "https://github.com/benedickcervantes/inspirewalletv2",
    private: false,
    horsepower: 820,
  },
  {
    name: "Inspire Admin V2 (Ultra)",
    githubRepo: "inspireadminv2",
    owner: "ultraelectronica",
    updatedAt: "2026-01-30T05:14:30Z",
    tag: "ADMIN PANEL",
    description: "Admin panel v2 under Ultra Electronica — Inspire Wallet operations and management UI.",
    language: "TypeScript",
    tags: ["#TypeScript", "#Admin", "#UltraElectronica"],
    github: "https://github.com/ultraelectronica/inspireadminv2",
    private: true,
    horsepower: 810,
  },
  {
    name: "Inspire Wallet V2 (Ultra)",
    githubRepo: "inspirewalletv2",
    owner: "ultraelectronica",
    updatedAt: "2026-01-29T07:34:10Z",
    tag: "WALLET APP",
    description: "Ultra Electronica fork of Inspire Wallet v2 — wallet client and transaction flows.",
    language: "JavaScript",
    tags: ["#JavaScript", "#InspireWallet", "#UltraElectronica"],
    github: "https://github.com/ultraelectronica/inspirewalletv2",
    private: true,
    horsepower: 790,
  },
  {
    name: "Inspire Wallet System",
    githubRepo: "InspireWallet-System",
    owner: "EngrBrianDev",
    updatedAt: "2026-01-27T08:10:36Z",
    tag: "FULL STACK",
    description: "Full Inspire Wallet system repository — integrated components across the wallet platform.",
    language: "JavaScript",
    tags: ["#JavaScript", "#FullStack", "#InspireWallet"],
    github: "https://github.com/EngrBrianDev/InspireWallet-System",
    private: true,
    horsepower: 890,
  },
  {
    name: "Inspire Wallet System (Ultra)",
    githubRepo: "InspireWallet-System",
    owner: "ultraelectronica",
    updatedAt: "2026-01-27T07:06:10Z",
    tag: "FULL STACK",
    description: "Ultra Electronica Inspire Wallet system — platform-wide wallet infrastructure and modules.",
    language: null,
    tags: ["#InspireWallet", "#FullStack", "#UltraElectronica"],
    github: "https://github.com/ultraelectronica/InspireWallet-System",
    private: true,
    horsepower: 880,
  },
];
